name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - binder

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: gkapfham/www.warmups.dev/binder
